### ISSUE TITLE
replicaCount of 3 causes a failure

### ISSUE THREAD

**Issue by rjrudin** [rjrudin/helm-playground#1]
I am working off of https://github.com/jkerr5/marklogic-kubernetes/tree/bugfix/postStartPID . 

I have the following config:

```
replicaCount: 3

auth:
 secretName: "ml-admin-secrets" 

resources:
  requests:      
    cpu: 2000m      
    memory: 4000Mi
  limits:
    cpu: 2000m
    memory: 4000Mi

persistence:
  enabled: true
  size: 20Gi
```

And I am running the following command after creating the "marklogic" namespace and the "ml-admin-secrets" secret (the above config all works fine with replicaCount=1); I'm running this from the root of the project:

    helm install --values values.yaml --namespace=marklogic dev ./charts

I get the following entries in minikube dashboard:

![image](https://user-images.githubusercontent.com/5026193/235712586-ffd80998-bc19-4480-9e04-347cd3885c4c.png)
