### ISSUE TITLE
Not able to get ports exposed via haProxy

### ISSUE THREAD

**Issue by rjrudin** [rjrudin/helm-playground#2]
My values.yaml:

```
replicaCount: 1

auth:
 secretName: "ml-admin-secrets" 

resources:
  requests:      
    cpu: 2000m      
    memory: 4000Mi
  limits:
    cpu: 2000m
    memory: 4000Mi

persistence:
  enabled: true
  size: 20Gi

haproxy:
  enabled: true
  service:    
    type: LoadBalancer
```

The service starts up fine, but I can't access http://localhost:8001 . I think https://docs.marklogic.com/11.0/guide/kubernetes-guide/en/accessing-marklogic-server-in-a-kubernetes-cluster/haproxy-load-balancer/configuration.html suggests that the above config should automatically expose 8000, 8001, and 8002.
